In [10]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as mpl
import scipy as sy
import tensorflow as tf
import keras as ke
import torch as pt

In [7]:
foodFP = pd.read_csv ('../Final_Project/food-footprints.csv')
foodFP

,Entity,Code,Year,"GHG emissions per kilogram (Poore & Nemecek, 2018)"
0,Apples,NaN,2010,0.43
1,Bananas,NaN,2010,0.86
2,Barley,NaN,2010,1.18
3,Beef (beef herd),NaN,2010,99.48
4,Beef (dairy herd),NaN,2010,33.30
...,...,...,...,...
33,Soymilk,NaN,2010,0.98
34,Tofu (soybeans),NaN,2010,3.16
35,Tomatoes,NaN,2010,2.09
36,Wheat & Rye,NaN,2010,1.57
37,Wine,NaN,2010,1.79

In [13]:
# view data shape

In [ ]:
#view different data types

In [11]:
# rename columns

In [12]:
#make numeric

In [ ]:
# drop NaN

In [ ]:
#plots to see normality